// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDFhQlFkxvjUZU45jFQt2VA_rC17DhI0',
    appId: '1:442013492539:web:bff4456a2873222e2c431e',
    messagingSenderId: '442013492539',
    projectId: 'proyecto-integrador-beabb',
    authDomain: 'proyecto-integrador-beabb.firebaseapp.com',
    storageBucket: 'proyecto-integrador-beabb.appspot.com',
    measurementId: 'G-JLSWYH8W4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyfrO0O_lcsTqQqKgtAjke9hRQbk2nS8U',
    appId: '1:442013492539:android:98ac0541c34f93aa2c431e',
    messagingSenderId: '442013492539',
    projectId: 'proyecto-integrador-beabb',
    storageBucket: 'proyecto-integrador-beabb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzm4gL_mEipG1gtfIRscIk0_hHRBAUgp0',
    appId: '1:442013492539:ios:15de16d4e2bc769b2c431e',
    messagingSenderId: '442013492539',
    projectId: 'proyecto-integrador-beabb',
    storageBucket: 'proyecto-integrador-beabb.appspot.com',
    iosBundleId: 'com.example.control',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzm4gL_mEipG1gtfIRscIk0_hHRBAUgp0',
    appId: '1:442013492539:ios:15de16d4e2bc769b2c431e',
    messagingSenderId: '442013492539',
    projectId: 'proyecto-integrador-beabb',
    storageBucket: 'proyecto-integrador-beabb.appspot.com',
    iosBundleId: 'com.example.control',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxDFhQlFkxvjUZU45jFQt2VA_rC17DhI0',
    appId: '1:442013492539:web:4828959f1dcfbe7b2c431e',
    messagingSenderId: '442013492539',
    projectId: 'proyecto-integrador-beabb',
    authDomain: 'proyecto-integrador-beabb.firebaseapp.com',
    storageBucket: 'proyecto-integrador-beabb.appspot.com',
    measurementId: 'G-BRMPFPQ3T1',
  );
}
